### ISSUE TITLE
Checkbox for option minified CSS output (or not)

### ISSUE THREAD

**Issue by jacquesulje** [the-jake-group/wp-less-compiler#2]
Very nice plugin, simple and elegant, like it very much.

One request though and a possible improvement: the css stylesheet that is created is minified by default, it would be useful if the user could choose an option: minified css output or not. Readable CSS might come in handy during development, minified CSS after.

Is it possibe to add a checkbox (Minify CSS) to the options screen, save the value as an option and use it in a conditional statement when the compiling takes place, something like this:

if ( self::_get_wp_option( "minified-css" ) == 'minfiedcss' ) $css_string = $this->_minify_css( $this->css_text );
else $css_string = $this->css_text;

Is something like this a possibility?

Kind regards

Jacques Uljé

**Comment by tybruffy** [comment]
Excellent idea,  I've created a separate branch with this functionality.  Would you mind downloading and testing it for me?  If everything works as expected I can go ahead and merge this in.

https://github.com/the-jake-group/wp-less-compiler/tree/compress-option

The compress option is selected at the time of compression, rather than storing it in the database.  This makes it easier to switch back and forth I think, and keeps us from adding to many items to the database.

Let me know if everything works as you expect.

**Comment by jacquesulje** [comment]
Thank you for your swift reply.

I've tested your changes and everything works like a charm!

I will keep the changes for now and hope the improvements will be implemented in the next update of your awesome plugin.

Many thanks!

**Comment by jacquesulje** [comment]
Thank you for your swift reply.

I've tested your changes and everything works like a charm!

I will keep the changes for now and hope the improvements will be implemented in the next update of your awesome plugin.

Many thanks!

Van: Tyler Bruffy [mailto:notifications@github.com] 
Verzonden: donderdag 4 september 2014 21:14
Aan: the-jake-group/wp-less-compiler
CC: jacquesulje
Onderwerp: Re: [wp-less-compiler] Checkbox for option minified CSS output (or not) (#2)

Excellent idea, I've created a separate branch with this functionality. Would you mind downloading and testing it for me? If everything works as expected I can go ahead and merge this in.

https://github.com/the-jake-group/wp-less-compiler/tree/compress-option

The compress option is selected at the time of compression, rather than storing it in the database. This makes it easier to switch back and forth I think, and keeps us from adding to many items to the database.

Let me know if everything works as you expect.
